spring:
  application:
    name: BookingSystemCinema

  # ===== SQL Server =====
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BookingCinemaDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # ===== JPA / Hibernate =====
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

  # ===== Redis =====
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

  # ===== Thymeleaf =====
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

# ===== JWT Configuration =====
jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
  expiration: 86400000
